/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var a=Object.defineProperty;var l=Object.getOwnPropertyDescriptor;var d=Object.getOwnPropertyNames;var p=Object.prototype.hasOwnProperty;var y=(t,e)=>{for(var i in e)a(t,i,{get:e[i],enumerable:!0})},f=(t,e,i,r)=>{if(e&&typeof e=="object"||typeof e=="function")for(let o of d(e))!p.call(t,o)&&o!==i&&a(t,o,{get:()=>e[o],enumerable:!(r=l(e,o))||r.enumerable});return t};var u=t=>f(a({},"__esModule",{value:!0}),t);var g={};y(g,{default:()=>s});module.exports=u(g);var n=require("obsidian"),s=class extends n.Plugin{async onload(){this.registerDomEvent(document,"keydown",e=>{if(e.key==="Enter"&&!e.shiftKey&&!e.ctrlKey&&!e.altKey&&!e.metaKey){let i=this.app.workspace.getActiveViewOfType(n.MarkdownView);if(i&&i.editor.hasFocus()){let r=i.editor,o=r.getCursor(),c=r.getLine(o.line);/^(\s*)([-*+]|\d+\.|>|\||```|~~~|[-*+]\s?\[[ xX]\])(\s|$)/.test(c)||(e.preventDefault(),e.stopPropagation(),this.insertDoubleNewline(r))}}},!0)}insertDoubleNewline(e){e.replaceSelection(`

`)}};
